import { AdjustmentsIcon as IconAdjustments } from "@heroicons/react/solid";
import {
  // GithubLogo as IconGitHub,
  // LinkedinLogo as IconLinkedIn,
  // MediumLogo as IconMedium,
  // TelegramLogo as IconTelegram,
  // TwitterLogo as IconTwitter,
  // YoutubeLogo as IconYouTube,
  CalendarBlank as IconCalendar,
  CaretDown as IconCaretDown,
  CaretUp as IconCaretUp,
  Chats as IconMessage,
  Check as IconCheck,
  CheckCircle as IconCheckCircle,
  Database as IconDatabase,
  Function as IconFunction,
  GearSix as IconGear,
  HardDrives as IconStorage,
  Key as IconKey,
  List as IconMenu,
  LockLaminated as IconSignUp,
  LockSimple as IconSignOut,
  LockSimpleOpen as IconSignIn,
  Rewind as IconRewind,
  Timer as IconTimer,
} from "phosphor-react";
import {
  FaCircle as IconCircle,
  FaDev as IconDev,
  FaDiscord as IconDiscord,
  FaGithub as IconGitHub,
  FaGlobe as IconWebsite,
  FaLinkedin as IconLinkedIn,
  FaMedium as IconMedium,
  FaMoon as IconLightTheme,
  FaProductHunt as IconProductHunt,
  FaStarHalf as IconSystemTheme,
  FaSun as IconDarkTheme,
  FaTelegram as IconTelegram,
  FaTwitter as IconTwitter,
  FaYoutube as IconYouTube,
} from "react-icons/fa";

export {
  IconAdjustments,
  IconCalendar,
  IconCaretDown,
  IconCaretUp,
  IconCheck,
  IconCheckCircle,
  IconCircle,
  IconDarkTheme,
  IconDatabase,
  IconDev,
  IconDiscord,
  IconFunction,
  IconGear,
  IconGitHub,
  IconKey,
  IconLightTheme,
  IconLinkedIn,
  IconMedium,
  IconMenu,
  IconMessage,
  IconProductHunt,
  IconRewind,
  IconSignIn,
  IconSignOut,
  IconSignUp,
  IconStorage,
  IconSystemTheme,
  IconTelegram,
  IconTimer,
  IconTwitter,
  IconWebsite,
  IconYouTube,
};
