import { AdjustmentsIcon as IconAdjustments } from "@heroicons/react/solid";
import {
  // General
  CalendarBlank as IconCalendar,
  CaretDown as IconCaretDown,
  Chats as IconMessage,
  Check as IconCheck,
  CheckCircle as IconCheckCircle,
  Database as IconDatabase,
  Function as IconFunction,
  GearSix as IconGear,
  HardDrives as IconStorage,
  Key as IconKey,
  List as IconMenu,
  LockLaminated as IconSignUp,
  LockSimple as IconSignOut,
  LockSimpleOpen as IconSignIn,
  Rewind as IconRewind,
  Timer as IconTimer,
  // External
  // DiscordLogo as IconDiscord,
  // GithubLogo as IconGitHub,
  // LinkedinLogo as IconLinkedIn,
  // MediumLogo as IconMedium,
  // TelegramLogo as IconTelegram,
  // TwitterLogo as IconTwitter,
  // YoutubeLogo as IconYouTube,
} from "phosphor-react";
import {
  // General
  FaCircle as IconCircle,
  FaGlobe as IconWebsite,
  FaMoon as IconLight,
  FaSun as IconDark,

  // External
  FaDev as IconDev,
  FaDiscord as IconDiscord,
  FaGithub as IconGitHub,
  FaLinkedin as IconLinkedIn,
  FaMedium as IconMedium,
  FaTelegram as IconTelegram,
  FaTwitter as IconTwitter,
  FaYoutube as IconYouTube,
  FaProductHunt as IconProductHunt,
} from "react-icons/fa";

export {
  IconAdjustments,
  IconCalendar,
  IconCaretDown,
  IconCheck,
  IconCheckCircle,
  IconCircle,
  IconDark,
  IconDatabase,
  IconDev,
  IconDiscord,
  IconFunction,
  IconGear,
  IconGitHub,
  IconKey,
  IconLight,
  IconLinkedIn,
  IconMedium,
  IconMenu,
  IconMessage,
  IconProductHunt,
  IconRewind,
  IconSignIn,
  IconSignOut,
  IconSignUp,
  IconStorage,
  IconTelegram,
  IconTimer,
  IconTwitter,
  IconWebsite,
  IconYouTube,
};
